// Code generated by Kitex v0.4.4. DO NOT EDIT.

package cos

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	cos "toktik/service/video/kitex_gen/cos"
)

func serviceInfo() *kitex.ServiceInfo {
	return cosServiceInfo
}

var cosServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Cos"
	handlerType := (*cos.Cos)(nil)
	methods := map[string]kitex.MethodInfo{
		"Upload": kitex.NewMethodInfo(uploadHandler, newCosUploadArgs, newCosUploadResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "cos",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func uploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cos.CosUploadArgs)
	realResult := result.(*cos.CosUploadResult)
	success, err := handler.(cos.Cos).Upload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCosUploadArgs() interface{} {
	return cos.NewCosUploadArgs()
}

func newCosUploadResult() interface{} {
	return cos.NewCosUploadResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Upload(ctx context.Context, req *cos.UploadReq) (r *cos.UploadResp, err error) {
	var _args cos.CosUploadArgs
	_args.Req = req
	var _result cos.CosUploadResult
	if err = p.c.Call(ctx, "Upload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
